### ISSUE TITLE
Does not work with MySQL

### ISSUE THREAD

**Issue by Goldsmith42** [spion/anydb-sql-migrations#1]
MySQL doesn't like the `text` type.

```
Error: ER_BLOB_KEY_WITHOUT_LENGTH: BLOB/TEXT column 'version' used in key specification without a key length in query `CREATE TABLE IF NOT EXISTS `_migrations` (`version` text PRIMARY KEY)` in tx 1 with params []
```

Changing it to something like `VARCHAR(100)` works as a workaround.

**Comment by spion** [comment]
We can add a `db.dialect()` method in anydb-sql that returns the dialect, and then use that method to decide the `dataType` for `version` to be `varchar(255)` for MySQL and `text` for everything else.
