### ISSUE TITLE
1.0.9 breaks `up` and `down` migrations that don't return a Promise

### ISSUE THREAD

**Issue by whoeverest** [spion/anydb-sql-migrations#4]
Okay, so I guess what happened is pretty rare, but anyways, documenting it here for the unfortunate person from the future that stumbles upon the same problem.

After upgrading to from `1.0.8` to `1.0.12` (that's my case, but I think the breaking change was introduced in `1.0.9`) after running `migrate.js --execute` I got the following exception:

```
whoeverest@fb186ab98eeb:/src/server$ ./scripts/migrate.js --execute
TypeError: Cannot read property 'then' of undefined
    at runSingle (/src/server/node_modules/anydb-sql-migrations/lib/index.js:52:21)
    at /src/server/node_modules/anydb-sql-migrations/lib/index.js:56:197
```

Solution: **I made sure the `up` and `down` functions return a Promise**.  I guess this was always the idea and it was my fault for not returning, but it worked for some time. Then I upgraded and it broke.

It's not a problem with the library so feel free to close the issue, just documenting what happened.

**Comment by spion** [comment]
Both up and down should definitely always return promises. If thats not the case, multiple migrations may be started in parallel which could cause serious issues.
